version: "3"
services:
  gamma-frontend:
    image: cthit/gamma-frontend:development
    environment:
      HTTP_PROXY: http://gamma-backend:8081
    networks:
      - gamma
    ports:
      - 3000:3000

  gamma-backend:
    image: cthit/gamma-backend
    environment:
      # Default admin user name = admin
      # Default admin password  = password

      DB_HOST: gamma-db
      DB_PORT: 5432
      DB_NAME: gamma
      DB_USER: gamma
      DB_PASSWORD: gamma

      REDIS_HOST: gamma-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""

      DEFAULT_CLIENT_NAME: wiki
      DEFAULT_CLIENT_ID: wiki
      DEFAULT_CLIENT_SECRET: wiki
      DEFAULT_REDIRECT_URI: http://localhost:4000/wiki/index.php/Special:OAuth2Client/callback

      SERVER_PORT: 8081
      FRONTEND_REDIRECT_URI: http://localhost:3000/login
      SUCCESSFUL_LOGIN: http://localhost:3000
      CORS_ALLOWED_ORIGIN: http://localhost:3000
      BACKEND_URI: http://localhost:8081
      PRODUCTION: "false"
      COOKIE_DOMAIN: localhost
    networks:
      - gamma
    ports:
      - 8081:8081

  gamma-redis:
    image: redis:5.0
    networks:
      - gamma

  gamma-db:
    image: postgres:10
    environment:
      POSTGRES_USER: gamma
      POSTGRES_DB: gamma
      POSTGRES_PASSWORD: gamma
    networks:
      - gamma

networks:
  gamma:
    external: true
