services:
  wiki:
    build:
      context: mediawiki
      dockerfile: Dockerfile
    image: ghcr.io/cthit/mediawiki-gamma:latest
    environment:
      WIKI_NAME: digITpedia
      CLIENT_ID: PLACEHOLDER_ID
      CLIENT_SECRET: PLACEHOLDER_SECRET
      PROVIDER_URL: https://auth.chalmers.it
      WIKI_PATH: /wiki
      DB_SERVER: wiki-db
      DB_NAME: wiki
      DB_USER: wiki
      DB_PASSWORD: wiki
      DB_PREFIX: ""
      SECRET_KEY: dasdasdasd
      UPGRADE_KEY: dasd
      ROOT_URL: http://localhost:4000
    ports:
      - 4001:80
    volumes:
      - ./images:/var/www/html/images

  wiki-proxy:
    build:
      context: proxy
      dockerfile: Dockerfile
    environment:
      WIKI_DOMAIN: localhost
      WIKI_PATH: wiki
      WIKI_HOST: wiki
    image: cthit/mediawiki-proxy:latest
    ports:
      - 4000:80

  wiki-db:
    image: mariadb:10.5
    environment:
      MYSQL_USER: wiki
      MYSQL_DATABASE: wiki
      MYSQL_PASSWORD: wiki
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
