version: "3"
services:
  wiki:
    build:
      context: mediawiki
      dockerfile: Dockerfile
    image: cthit/mediawiki:latest
    environment:
      GAMMA_CLIENT_ID: OwjtOwnraqUbJEuvdpQ7YTBbIyII4OA11fB4b1woqvVPKxLiQzZ8dl4Alz1WFbHZGpCcBoDhzdm
      GAMMA_CLIENT_SECRET: 3bkxqBQk3POPeEYK8Mbsfu1rw6FhQaNARpfLXe4Cio84FVMSeo1va73TLbPkbtNGFxyhgnm7Q3F
      GAMMA_AUTH: http://localhost:3000/api/oauth/authorize
      GAMMA_TOKEN: http://gamma-backend:8081/api/oauth/token
      GAMMA_USER: http://gamma-backend:8081/api/users/me
      GAMMA_REDIRECT: http://localhost:4000/wiki/index.php/Special:OAuth2Client/callback
      GAMMA_AUTHORITY: admin
      WIKI_NAME: digITpedia
      WIKI_PATH: /wiki
      DB_SERVER: wiki-db
      DB_NAME: wiki
      DB_USER: wiki
      DB_PASSWORD: wiki
      DB_PREFIX: ""
      SECRET_KEY: dasdasdasd
      UPGRADE_KEY: dasd
      ROOT_URL: http://localhost:4000
    networks:
      - default
      - gamma
    ports:
      - 4001:80
    volumes:
      - ./images:/var/www/html/images

  wiki-proxy:
    build:
      context: proxy
      dockerfile: Dockerfile
    environment:
      WIKI_DOMAIN: localhost
      WIKI_PATH: wiki
      WIKI_HOST: wiki
    image: cthit/mediawiki-proxy:latest
    networks:
      - default
    ports:
      - 4000:80

  wiki-db:
    image: mariadb:10.5
    environment:
      MYSQL_USER: wiki
      MYSQL_DATABASE: wiki
      MYSQL_PASSWORD: wiki
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    networks:
      - default
      - gamma
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

networks:
  default:
  gamma:
    external: true
